version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [a1:89:9c:0e:de:3b:c0:c3:d1:82:40:8f:8b:ad:1f:4d]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook ./main.yml -i ./inventory.txt --private-key udacity.pem

workflows:
  configure_infrastructure_workflow:
    jobs:
      - configure_infrastructure
