version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          when: on_fail
          command: |
            sudo apt install awscli && \
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - a1:89:9c:0e:de:3b:c0:c3:d1:82:40:8f:8b:ad:1f:4d
      - run:
          name: Update packages
          command: |
            sudo apt update && \
            sudo apt install software-properties-common && \
            sudo add-apt-repository --yes --update ppa:ansible/ansible
      - run:
          name: Install Ansible
          command: |
            sudo apt install ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml -i inventory.txt

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Test job
          command: return 1
      - destroy_environment
      # - run: apk add --update curl
      # - run:
      #     name: smoke test
      #     command: |
      #       URL="https://blog.udacitys.com/"
      #       if curl -s --head ${URL}
      #       then
      #         return 0
      #       else
      #         return 1
      #       fi

workflows:
  rollback:
    jobs:
      - create_infrastructure
      - smoke_test:
          requires: [create_infrastructure]
